# -*- coding: utf-8 -*-
"""diffusion_of_microwave.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17UW9nnubi3oAnw_K1N0QNaYkoK1Qiq43
"""

# !pip install japanize-matplotlib

import numpy as np
import pandas as pd
import math
import japanize_matplotlib
from matplotlib import pyplot as plt

df = pd.read_excel("https://www.esri.cao.go.jp/jp/stat/shouhi/0403fukyuritsu.xls", header=2, skipfooter=2)

df = df.replace('\u3000\u3000', np.nan)
df = df.drop(0)
df["年"] = [math.floor(i) + 1925 if i > 30 else math.floor(i) + 1988 for i in df["調査項目"]]

plt.plot(df["年"], df["電子レンジ"], marker="o", label="電子レンジ")
plt.ylim(0, 100)
plt.xlabel("年")
plt.ylabel("電子レンジの普及率")
plt.savefig("microwave.pdf", format="pdf", dpi=300)

plt.plot(df["年"], df["電気冷蔵庫"], marker="o", label="電気冷蔵庫")
plt.ylim(0, 100)
plt.xlabel("年")
plt.ylabel("電子レンジと電気冷蔵庫の普及率")
plt.legend(reverse=True, loc='upper left')
plt.savefig("refrigerator.pdf", format="pdf", dpi=300)

