# -*- coding: utf-8 -*-
"""Diffusion_of_microwave.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/takeshinishimura/Agricultural_Markets/blob/main/Diffusion_of_microwave.ipynb
"""

import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt
import japanize_matplotlib

df = pd.read_excel("https://www.esri.cao.go.jp/jp/stat/shouhi/0403fukyuritsu.xls", header=2, skipfooter=2)
df.head()

df = df.replace('\u3000\u3000', np.nan)
df = df.drop(0)

nen = []
for i in df["調査項目"]:
    if i > 30:
        nen.append(math.floor(i) + 1925)
    else:
        nen.append(math.floor(i) + 1988)
df["年"] = nen

plt.scatter(df["年"], df["電子レンジ"], label="電子レンジ")
plt.ylim(0, 100)
plt.xlabel("年")
plt.ylabel("電子レンジの普及率")
plt.savefig("microwave.pdf", format="pdf", dpi=300)

plt.scatter(df["年"], df["電気冷蔵庫"], label="電気冷蔵庫")
plt.ylim(0, 100)
plt.xlabel("年")
plt.ylabel("電子レンジと電気冷蔵庫の普及率")
plt.legend(reverse=True)
plt.savefig("refrigerator.pdf", format="pdf", dpi=300)
